-- 001_initial_schema.sql
--
-- Mirrors the shape of data/mock-db.json exactly, by team decision. Every column
-- name matches the JSON key it came from, so the 176 existing data-access call
-- sites and the frontend keep working without a translation layer.
--
-- Consequences of that decision, recorded here rather than discovered later:
--   * Denormalised display columns are kept (faculty_name, student_name,
--     course_code, fees.first_name/last_name). They can drift from the row they
--     were copied from; nothing here prevents that.
--   * Nested arrays become jsonb (research milestones/uploads/students,
--     syllabus modules) rather than child tables.
--   * Primary keys are text, not serial. Ids are generated by the application
--     ('u1', 'c1', uuid, `p${Date.now()}`), so the database must accept whatever
--     the app supplies rather than assigning its own.

-- ── Reference ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS departments (
  department_id   text PRIMARY KEY,
  department_name text NOT NULL,
  department_code text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  user_id       text PRIMARY KEY,
  username      text,
  email         text NOT NULL UNIQUE,
  role          text NOT NULL CHECK (role IN ('student','faculty','admin','head','superadmin')),
  -- bcrypt digest. Never a plaintext password: see PasswordService.
  password_hash text,
  first_name    text,
  last_name     text,
  phone         text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Profile rows are keyed by user_id (1:1 with users), matching the JSON.
CREATE TABLE IF NOT EXISTS students (
  user_id    text PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  first_name text,
  last_name  text,
  branch     text,
  batch      text,
  cgpa       numeric(4,2),
  section    text,
  dob        date,
  phone      text,
  join_date  date,
  email      text
);

CREATE TABLE IF NOT EXISTS faculty (
  user_id       text PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  first_name    text,
  last_name     text,
  designation   text,
  department_id text REFERENCES departments(department_id),
  email         text,
  phone         text
);

CREATE TABLE IF NOT EXISTS courses (
  course_id    text PRIMARY KEY,
  course_name  text NOT NULL,
  course_code  text NOT NULL UNIQUE,
  credits      integer,
  semester     integer,
  faculty_id   text REFERENCES users(user_id),
  faculty_name text                                   -- denormalised display copy
);

-- ── Enrolment and academics ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS enrollment (
  enrollment_id text PRIMARY KEY,
  student_id    text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  course_id     text NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  year_id       text,
  status        text,
  section       text,
  UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS attendance_log (
  log_id     text PRIMARY KEY,
  student_id text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  course_id  text NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  date       date NOT NULL,
  status     text NOT NULL CHECK (status IN ('present','absent','excused')),
  -- Set when a row was created by approving leave, so the change is reversible.
  source          text,
  previous_status text,
  -- The application already upserts on this triple (audit M-01); the constraint
  -- makes the invariant real rather than conventional.
  UNIQUE (student_id, course_id, date)
);

CREATE TABLE IF NOT EXISTS assessments (
  assessment_id text PRIMARY KEY,
  course_id     text REFERENCES courses(course_id) ON DELETE CASCADE,
  name          text,
  type          text,
  max_marks     integer,
  weightage     integer,
  faculty_id    text REFERENCES users(user_id),
  date          date
);

CREATE TABLE IF NOT EXISTS marks_entry (
  entry_id       text PRIMARY KEY,
  student_id     text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  assessment_id  text NOT NULL,
  course_code    text,                                -- denormalised display copy
  marks_obtained numeric(6,2),
  max_marks      integer,
  grade          text,
  feedback_text  text,
  -- Enforces the "marks lock" the application advertises. It was bypassable
  -- through a second route (audit H-03); at this level it is not.
  UNIQUE (student_id, assessment_id)
);

CREATE TABLE IF NOT EXISTS syllabus_progress (
  course_id  text NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  section    text NOT NULL,
  progress   integer CHECK (progress BETWEEN 0 AND 100),
  updated_by text REFERENCES users(user_id),
  updated_at date,
  modules    jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- The JSON has no id for these rows; course+section is the natural key.
  PRIMARY KEY (course_id, section)
);

CREATE TABLE IF NOT EXISTS timetable (
  slot_id     text PRIMARY KEY,
  day         text NOT NULL,
  "time"      text NOT NULL,                          -- 'time' is reserved; kept as text to match the app
  course_id   text REFERENCES courses(course_id) ON DELETE CASCADE,
  course_code text,                                   -- denormalised display copy
  course_name text,                                   -- denormalised display copy
  room        text,
  type        text,
  section     text
);

CREATE TABLE IF NOT EXISTS submissions (
  submission_id text PRIMARY KEY,
  student_id    text REFERENCES users(user_id) ON DELETE CASCADE,
  assessment_id text,
  notes         text,
  status        text,
  submitted_at  timestamptz
);

-- ── Workflows ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS leave_applications (
  leave_id     text PRIMARY KEY,
  student_id   text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  student_name text,                                  -- denormalised display copy
  leave_type   text,
  start_date   date,
  end_date     date,
  reason       text,
  status       text CHECK (status IN ('pending','approved','rejected')),
  applied_on   date
);

CREATE TABLE IF NOT EXISTS attendance_requests (
  request_id     text PRIMARY KEY,
  student_id     text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  student_name   text,                                -- denormalised display copy
  course_id      text REFERENCES courses(course_id) ON DELETE CASCADE,
  course_code    text,                                -- denormalised display copy
  date           date,
  reason         text,
  admin_status   text,
  admin_reason   text,
  faculty_status text,
  created_at     timestamptz
);

CREATE TABLE IF NOT EXISTS research_projects (
  project_id       text PRIMARY KEY,
  title            text,
  abstract         text,
  supervisor_id    text REFERENCES users(user_id),
  supervisor_name  text,                              -- denormalised display copy
  student_id       text REFERENCES users(user_id),
  student_name     text,                              -- denormalised display copy
  status           text,
  progress         integer,
  submission_notes text,
  faculty_feedback text,
  -- Nested arrays in the JSON. Kept as documents rather than child tables, per
  -- the decision to mirror the existing shape.
  students   jsonb NOT NULL DEFAULT '[]'::jsonb,
  uploads    jsonb NOT NULL DEFAULT '[]'::jsonb,
  milestones jsonb NOT NULL DEFAULT '[]'::jsonb
);

-- ── Community ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS discussion_posts (
  post_id     text PRIMARY KEY,
  author_id   text REFERENCES users(user_id) ON DELETE SET NULL,
  author_name text,                                   -- denormalised display copy
  author_role text,
  -- NOTE: the seed stores a course *code* here ('CS201'), not a course_id.
  -- No foreign key, because the values do not reference courses.course_id.
  course_id   text,
  title       text,
  content     text,
  tag         text,
  reply_count integer NOT NULL DEFAULT 0,
  created_at  timestamptz
);

CREATE TABLE IF NOT EXISTS discussion_replies (
  reply_id    text PRIMARY KEY,
  post_id     text NOT NULL REFERENCES discussion_posts(post_id) ON DELETE CASCADE,
  author_id   text REFERENCES users(user_id) ON DELETE SET NULL,
  author_name text,                                   -- denormalised display copy
  author_role text,
  content     text,
  created_at  timestamptz
);

-- ── Institution ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS events (
  event_id    text PRIMARY KEY,
  event_name  text NOT NULL,
  date        date,
  venue       text,
  description text
);

CREATE TABLE IF NOT EXISTS resources (
  resource_id text PRIMARY KEY,
  name        text NOT NULL,
  type        text,
  capacity    integer,
  location    text,
  status      text
);

CREATE TABLE IF NOT EXISTS resource_bookings (
  booking_id     text PRIMARY KEY,
  resource_id    text REFERENCES resources(resource_id) ON DELETE CASCADE,
  resource_name  text,                                -- denormalised display copy
  requested_by   text REFERENCES users(user_id),
  requester_name text,                                -- denormalised display copy
  date           date,
  time_slot      text,
  purpose        text,
  status         text,
  created_at     timestamptz
);

CREATE TABLE IF NOT EXISTS fees (
  fee_id     text PRIMARY KEY,
  student_id text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  first_name text,                                    -- denormalised display copy
  last_name  text,                                    -- denormalised display copy
  -- The seed uses "type"; POST /fees writes "fee_type". Both are kept so neither
  -- path silently loses data. Worth reconciling later (audit note).
  type       text,
  fee_type   text,
  semester   text,
  amount     numeric(12,2),
  due_date   date,
  paid_date  text,
  status     text
);

-- ── Indexes for the access patterns the app actually uses ────────────────────

CREATE INDEX IF NOT EXISTS idx_enrollment_student    ON enrollment (student_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_course     ON enrollment (course_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student    ON attendance_log (student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_course_day ON attendance_log (course_id, date);
CREATE INDEX IF NOT EXISTS idx_marks_student         ON marks_entry (student_id);
CREATE INDEX IF NOT EXISTS idx_marks_assessment      ON marks_entry (assessment_id);
CREATE INDEX IF NOT EXISTS idx_leave_student         ON leave_applications (student_id);
CREATE INDEX IF NOT EXISTS idx_leave_status          ON leave_applications (status);
CREATE INDEX IF NOT EXISTS idx_replies_post          ON discussion_replies (post_id);
CREATE INDEX IF NOT EXISTS idx_fees_student          ON fees (student_id);
CREATE INDEX IF NOT EXISTS idx_timetable_section     ON timetable (section);
CREATE INDEX IF NOT EXISTS idx_courses_faculty       ON courses (faculty_id);
CREATE INDEX IF NOT EXISTS idx_assessments_faculty   ON assessments (faculty_id);
CREATE INDEX IF NOT EXISTS idx_attreq_student        ON attendance_requests (student_id);
CREATE INDEX IF NOT EXISTS idx_submissions_student   ON submissions (student_id);
