/**
 * uploads.service.ts — document metadata and access control.
 *
 * Bytes live on disk under a random UUID name; this records what each file is,
 * who uploaded it, and what it is attached to. Nothing else in the application
 * touches the filesystem.
 */

import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectPinoLogger, PinoLogger } from 'nestjs-pino';
import { randomUUID } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { InMemoryDbService } from '../database/in-memory-db.service';
import { ErrorCode, errorBody } from '../common/errors/error-codes';
import { UPLOAD_DIR, sanitizeOriginalName } from './upload.config';
import { isSameCollege, writeCollegeId } from '../common/tenancy/scope-to-college';
import type { Role } from '../auth/jwt-payload';

/** What a document is attached to. Determines who may read it. */
export type UploadContext =
  | 'leave'
  | 'attendance_request'
  | 'research_milestone'
  | 'assessment_submission';

export const UPLOAD_CONTEXTS: UploadContext[] = [
  'leave',
  'attendance_request',
  'research_milestone',
  'assessment_submission',
];

export interface UploadRecord {
  file_id: string;
  stored_name: string; // the UUID filename on disk
  original_name: string; // sanitised, shown to users
  mime_type: string;
  size_bytes: number;
  context: UploadContext;
  uploaded_by: string;
  uploaded_at: string;
  college_id?: string | null;
}

/** Staff who may read any document, because reviewing them is their job. */
const REVIEWER_ROLES: Role[] = ['faculty', 'admin', 'head', 'superadmin'];

@Injectable()
export class UploadsService {
  constructor(
    private readonly db: InMemoryDbService,
    @InjectPinoLogger(UploadsService.name) private readonly logger: PinoLogger,
  ) {}

  /** The collection is created lazily so no migration is needed for the JSON store. */
  private get records(): UploadRecord[] {
    const store = this.db as any;
    if (!store.uploads) store.uploads = [];
    return store.uploads;
  }

  record(
    file: Express.Multer.File,
    context: UploadContext,
    userId: string,
    actorCollegeId: string | null,
  ): UploadRecord {
    const entry: UploadRecord = {
      file_id: randomUUID(),
      stored_name: file.filename,
      original_name: sanitizeOriginalName(file.originalname),
      mime_type: file.mimetype,
      size_bytes: file.size,
      context,
      uploaded_by: userId,
      uploaded_at: new Date().toISOString(),
      college_id: writeCollegeId(actorCollegeId),
    };

    this.records.push(entry);
    this.db.persist();

    this.logger.info(
      {
        fileId: entry.file_id,
        context,
        userId,
        sizeBytes: entry.size_bytes,
        mimeType: entry.mime_type,
      },
      'Document uploaded',
    );

    return entry;
  }

  findById(fileId: string): UploadRecord {
    const found = this.records.find((r) => r.file_id === fileId);
    if (!found) {
      throw new NotFoundException(
        errorBody(ErrorCode.RESOURCE_NOT_FOUND, 'Document not found'),
      );
    }
    return found;
  }

  /**
   * Resolve a record to a path on disk, refusing anything outside UPLOAD_DIR.
   *
   * `stored_name` is generated by us, so traversal should be impossible — but
   * this is the one place a bad value would become filesystem access, and the
   * check costs nothing.
   */
  resolvePath(record: UploadRecord): string {
    const full = path.resolve(UPLOAD_DIR, record.stored_name);
    if (!full.startsWith(path.resolve(UPLOAD_DIR) + path.sep)) {
      this.logger.error(
        { fileId: record.file_id, storedName: record.stored_name },
        'Upload path escaped the upload directory',
      );
      throw new NotFoundException(
        errorBody(ErrorCode.RESOURCE_NOT_FOUND, 'Document not found'),
      );
    }
    if (!fs.existsSync(full)) {
      // Metadata without bytes — the row outlived the file.
      this.logger.error(
        { fileId: record.file_id, path: full },
        'Upload metadata has no file on disk',
      );
      throw new NotFoundException(
        errorBody(
          ErrorCode.RESOURCE_NOT_FOUND,
          'Document is no longer available',
        ),
      );
    }
    return full;
  }

  /**
   * Who may download a document.
   *
   * These are medical certificates and coursework, so the default is "only the
   * person who uploaded it". Staff may read any document because approving leave
   * or reviewing a milestone requires seeing the attachment — a student may not
   * read another student's.
   *
   * TENANT_ISOLATION_DIAGNOSIS.md Group C: "staff" used to mean any faculty/
   * admin/head/superadmin at ANY college — a faculty member at college A
   * could download a medical certificate uploaded by a student at college B,
   * given only the file_id. The reviewer exemption now also requires the
   * reviewer's own college to match the document's.
   */
  assertCanRead(
    record: UploadRecord,
    userId: string,
    role: Role,
    collegeId: string | null,
  ): void {
    if (record.uploaded_by === userId) return;
    if (REVIEWER_ROLES.includes(role) && isSameCollege(record, collegeId)) return;

    this.logger.warn(
      { fileId: record.file_id, userId, role, owner: record.uploaded_by },
      'Blocked attempt to read another user document',
    );
    throw new ForbiddenException(
      errorBody(
        ErrorCode.NOT_RESOURCE_OWNER,
        'You do not have access to this document',
      ),
    );
  }

  /** Best-effort cleanup when a request fails after multer has written the file. */
  discard(file?: Express.Multer.File): void {
    if (!file?.path) return;
    fs.promises
      .unlink(file.path)
      .catch((err) =>
        this.logger.warn(
          { err, path: file.path },
          'Could not remove orphaned upload',
        ),
      );
  }
}
