/**
 * uploads.service.ts — document metadata and access control.
 *
 * Bytes live on disk under a random UUID name; this records what each file is,
 * who uploaded it, and what it is attached to. Nothing else in the application
 * touches the filesystem.
 */

import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectPinoLogger, PinoLogger } from 'nestjs-pino';
import { randomUUID } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { InMemoryDbService } from '../database/in-memory-db.service';
import { ErrorCode, errorBody } from '../common/errors/error-codes';
import { UPLOAD_DIR, sanitizeOriginalName } from './upload.config';
import type { Role } from '../auth/jwt-payload';

/** What a document is attached to. Determines who may read it. */
export type UploadContext =
  | 'leave'
  | 'attendance_request'
  | 'research_milestone'
  | 'assessment_submission'
  | 'profile_photo';

export const UPLOAD_CONTEXTS: UploadContext[] = [
  'leave',
  'attendance_request',
  'research_milestone',
  'assessment_submission',
  'profile_photo',
];

export const PHOTO_MIME_TYPES = ['image/jpeg', 'image/png'];

export interface UploadRecord {
  file_id: string;
  stored_name: string;      // the UUID filename on disk
  original_name: string;    // sanitised, shown to users
  mime_type: string;
  size_bytes: number;
  context: UploadContext;
  uploaded_by: string;
  uploaded_at: string;
}

/** Staff who may read any document, because reviewing them is their job. */
const REVIEWER_ROLES: Role[] = ['faculty', 'admin', 'head', 'superadmin'];

@Injectable()
export class UploadsService {
  constructor(
    private readonly db: InMemoryDbService,
    @InjectPinoLogger(UploadsService.name) private readonly logger: PinoLogger,
  ) {}

  /** The collection is created lazily so no migration is needed for the JSON store. */
  private get records(): UploadRecord[] {
    return this.db.uploads as UploadRecord[];
  }

  record(file: Express.Multer.File, context: UploadContext, userId: string): UploadRecord {
    const entry: UploadRecord = {
      file_id: randomUUID(),
      stored_name: file.filename,
      original_name: sanitizeOriginalName(file.originalname),
      mime_type: file.mimetype,
      size_bytes: file.size,
      context,
      uploaded_by: userId,
      uploaded_at: new Date().toISOString(),
    };

    this.records.push(entry);
    this.db.persist();

    this.logger.info(
      {
        fileId: entry.file_id,
        context,
        userId,
        sizeBytes: entry.size_bytes,
        mimeType: entry.mime_type,
      },
      'Document uploaded',
    );

    return entry;
  }

  findById(fileId: string): UploadRecord {
    const found = this.records.find((r) => r.file_id === fileId);
    if (!found) {
      throw new NotFoundException(
        errorBody(ErrorCode.RESOURCE_NOT_FOUND, 'Document not found'),
      );
    }
    return found;
  }

  /**
   * Resolve a record to a path on disk, refusing anything outside UPLOAD_DIR.
   *
   * `stored_name` is generated by us, so traversal should be impossible — but
   * this is the one place a bad value would become filesystem access, and the
   * check costs nothing.
   */
  resolvePath(record: UploadRecord): string {
    const full = path.resolve(UPLOAD_DIR, record.stored_name);
    if (!full.startsWith(path.resolve(UPLOAD_DIR) + path.sep)) {
      this.logger.error(
        { fileId: record.file_id, storedName: record.stored_name },
        'Upload path escaped the upload directory',
      );
      throw new NotFoundException(
        errorBody(ErrorCode.RESOURCE_NOT_FOUND, 'Document not found'),
      );
    }
    if (!fs.existsSync(full)) {
      // Metadata without bytes — the row outlived the file.
      this.logger.error({ fileId: record.file_id, path: full }, 'Upload metadata has no file on disk');
      throw new NotFoundException(
        errorBody(ErrorCode.RESOURCE_NOT_FOUND, 'Document is no longer available'),
      );
    }
    return full;
  }

  /**
   * Who may download a document.
   *
   * These are medical certificates and coursework, so the default is "only the
   * person who uploaded it". Staff may read any document because approving leave
   * or reviewing a milestone requires seeing the attachment — a student may not
   * read another student's, except a file attached to a research project they
   * are on. Staff are limited to documents from their own college.
   */
  private sameCollege(ownerId: string, readerId: string): boolean {
    const users = this.db.users ?? [];
    const owner = users.find((u: any) => u.user_id === ownerId);
    const reader = users.find((u: any) => u.user_id === readerId);
    // Records that predate college scoping have no college on either side.
    return (owner?.college_id ?? null) === (reader?.college_id ?? null);
  }

  assertCanRead(record: UploadRecord, userId: string, role: Role): void {
    if (record.uploaded_by === userId) return;
    // Staff review documents of their own college only.
    if (REVIEWER_ROLES.includes(role) && this.sameCollege(record.uploaded_by, userId)) return;
    // A file attached to a research project is shared with that project's team.
    const shared = (this.db.research_projects ?? []).some(
      (p: any) =>
        (p.uploads ?? []).some((u: any) => u.file_id === record.file_id) &&
        (p.supervisor_id === userId || (p.students ?? []).some((st: any) => st.user_id === userId)),
    );
    if (shared) return;

    this.logger.warn(
      { fileId: record.file_id, userId, role, owner: record.uploaded_by },
      'Blocked attempt to read another user document',
    );
    throw new ForbiddenException(
      errorBody(ErrorCode.NOT_RESOURCE_OWNER, 'You do not have access to this document'),
    );
  }

  /** Best-effort cleanup when a request fails after multer has written the file. */
  discard(file?: Express.Multer.File): void {
    if (!file?.path) return;
    fs.promises.unlink(file.path).catch((err) =>
      this.logger.warn({ err, path: file.path }, 'Could not remove orphaned upload'),
    );
  }
}
