export enum MeetingStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  RESCHEDULE_REQUESTED = 'RESCHEDULE_REQUESTED',
  DENIED = 'DENIED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}
